### ISSUE TITLE
v3/teams/{teamId}/conversations returning 403 ServiceError Unkown

### ISSUE THREAD

**Issue by carolinedpena** [MicrosoftDocs/msteams-docs#10741]
### Steps to reproduce

Seeing errors with code ServiceError and message Unknown when calling v3/teams/{teamId}/conversations API. Started a few hours ago. Tested it out with several teams and getting the same error for all of them.

### Expected behavior

We'd expect the message to be sent

### Actual behavior

RestError: Unknown

### Error details

Full error returned:
`2024-04-15T18:41:54.503372270Z RestError: Unknown
2024-04-15T18:41:54.503390371Z     at new RestError (/node_modules/@azure/ms-rest-js/dist/msRest.node.js:2480:28)
2024-04-15T18:41:54.503396371Z     at /node_modules/@azure/ms-rest-js/dist/msRest.node.js:3687:37
2024-04-15T18:41:54.503406972Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2024-04-15T18:41:54.503428172Z   code: 'ServiceError',
2024-04-15T18:41:54.503432773Z   statusCode: 403,
2024-04-15T18:41:54.503437073Z   request: WebResource {
2024-04-15T18:41:54.503441573Z     streamResponseBody: false,
2024-04-15T18:41:54.503445973Z     url: 'https://smba.trafficmanager.net/amer/v3/teams/19%3A0492f07041d44c5cb20bb7dd91299da6%40thread.skype/conversations',
2024-04-15T18:41:54.503450473Z     method: 'GET',
2024-04-15T18:41:54.503454773Z     headers: HttpHeaders { _headersMap: [Object] },
2024-04-15T18:41:54.503459174Z     body: undefined,
2024-04-15T18:41:54.503463374Z     query: undefined,
2024-04-15T18:41:54.503467574Z     formData: undefined,
2024-04-15T18:41:54.503472074Z     withCredentials: false,
2024-04-15T18:41:54.503476374Z     abortSignal: undefined,
2024-04-15T18:41:54.503480574Z     timeout: 0,
2024-04-15T18:41:54.503484874Z     onUploadProgress: undefined,
2024-04-15T18:41:54.503489175Z     onDownloadProgress: undefined,
2024-04-15T18:41:54.503493475Z     proxySettings: undefined,
2024-04-15T18:41:54.503497675Z     keepAlive: undefined,
2024-04-15T18:41:54.503501875Z     agentSettings: undefined,
2024-04-15T18:41:54.503506175Z     redirectLimit: undefined,
2024-04-15T18:41:54.503510475Z     operationSpec: {
2024-04-15T18:41:54.503520876Z       httpMethod: 'GET',
2024-04-15T18:41:54.503525176Z       path: 'v3/teams/{teamId}/conversations',
2024-04-15T18:41:54.503529576Z       urlParameters: [Array],
2024-04-15T18:41:54.503533776Z       responses: [Object],
2024-04-15T18:41:54.503538076Z       serializer: [Serializer]
2024-04-15T18:41:54.503542377Z     }
2024-04-15T18:41:54.503546677Z   },
2024-04-15T18:41:54.503550877Z   response: {
2024-04-15T18:41:54.503555177Z     body: '{"error":{"code":"ServiceError","message":"Unknown"}}',
2024-04-15T18:41:54.503560077Z     headers: HttpHeaders { _headersMap: [Object] },
2024-04-15T18:41:54.503564677Z     status: 403
2024-04-15T18:41:54.503568878Z   },
2024-04-15T18:41:54.503573178Z   body: undefined
2024-04-15T18:41:54.503577378Z }`

**Comment by carolinedpena** [comment]
I've confirmed that the error is coming from the following method. We've tried it with both the optional teams id param:

`             
try {
   teamChannels = await TeamsInfo.getTeamChannels(context);
} catch(err) {
    console.log('error in getting teams channels')
    console.log(err)
}   
`

`
try {
   teamChannels = await TeamsInfo.getTeamChannels(context, context.activity.channelData.teamsTeamId);
} catch(err) {
    console.log('error in getting teams channels')
    console.log(err)
}
`

Both return the following:
2024-04-16T13:57:39.763599244Z error in getting teams channels
2024-04-16T13:57:39.766050531Z RestError: Unknown 
2024-04-16T13:57:39.766074232Z  {
2024-04-16T13:57:39.766133434Z   "name": "RestError",
2024-04-16T13:57:39.766140634Z   "code": "ServiceError",
2024-04-16T13:57:39.766145834Z   "statusCode": 403,
2024-04-16T13:57:39.766150635Z   "request": {
2024-04-16T13:57:39.766155435Z     "streamResponseStatusCodes": {},
2024-04-16T13:57:39.766160335Z     "url": "https://smba.trafficmanager.net/amer/v3/teams/19%3AQD_Odb-mcvY4MUZyHrNYdm5VoNKgj7vSfDfqdO_Rlok1%40thread.tacv2/conversations",
2024-04-16T13:57:39.766165535Z     "method": "GET",
2024-04-16T13:57:39.766176136Z     "headers": {
2024-04-16T13:57:39.766181036Z       "_headersMap": {
2024-04-16T13:57:39.766185736Z         "authorization": "REDACTED",
2024-04-16T13:57:39.766190536Z         "user-agent": "core-http/3.0.4 Node/v14.21.3 OS/(x64-Linux-5.15.145.2-1.cm2)"
2024-04-16T13:57:39.766195536Z       }
2024-04-16T13:57:39.766199736Z     },
2024-04-16T13:57:39.766204237Z     "withCredentials": false,
2024-04-16T13:57:39.766209037Z     "timeout": 0,
2024-04-16T13:57:39.766229037Z     "requestId": "fc38fe88-27cf-446f-83c4-14159da00556"
2024-04-16T13:57:39.766234038Z   },
2024-04-16T13:57:39.766238538Z   "details": {
2024-04-16T13:57:39.766243138Z     "error": {
2024-04-16T13:57:39.766247638Z       "code": "ServiceError",
2024-04-16T13:57:39.766252338Z       "message": "Unknown"
2024-04-16T13:57:39.766257038Z     }
2024-04-16T13:57:39.766261639Z   },
2024-04-16T13:57:39.766266139Z   "message": "Unknown"
2024-04-16T13:57:39.766270739Z }

We've confirmed the error is present with botbuilder v4.16.0 and the latest botbuilder v4.22.2

**Comment by iraquint** [comment]
Also running into this issue on botbuilder (v3.30.0). @carolinedpena thanks for opening!

**Comment by ChetanSharma-msft** [comment]
Hello @carolinedpena - Thanks for raising your query.
Could you please share the repro steps and code snippets so that we can quickly check and investigate on this?

**Comment by carolinedpena** [comment]
Hi @ChetanSharma-msft - we're encountering this error in 2 different scenarios where we are using the TeamsInfo.getTeamChannels method. First, we are sending an adaptive card to the user and crafting a deep link to that message. The variable ref in the block below is a conversation reference that was retrieved earlier in the user's interaction with the bot. The userChannelTeamId on the body object as well:

`
try {
        const messageId = await context.sendActivity(assignmentCard);
        
        let channelName: any;
        let channelId: any;
        
        // get teams aad id
        const teamsDetails = await TeamsInfo.getTeamDetails(context, body.userChannelTeamId);
        const teamsAadId = teamsDetails.aadGroupId;

        if (!ref.conversation.name) {
          const channelObj = await TeamsInfo.getTeamChannels(context, body.userChannelTeamId)
          channelId = ref.conversation.id;

          if (ref.conversation.id.includes(";")) {
            channelId = ref.conversation.id.split(";")[0]
          }

          const channelN = channelObj.find(channel => channel.id === channelId);

          channelName = channelN?.name
        } else {
          channelName = ref.conversation.name
        }

        // check if message is a reply to an existing discussion thread and extract the parent id if it is
        let parentId = '';
        
        if (context.activity.conversation.id.includes('messageid')) {
            parentId = context.activity.conversation.id.split(';')[1].split('=')[1];
        }

        // creating discussion thread url to save to assignments table
        discussionThreadURL = `https://teams.microsoft.com/l/message/${channelId}/${messageId?.id}?tenantId=${context.activity.conversation.tenantId}&groupId=${teamsAadId}&parentMessageId=${parentId.length > 0 ? parentId : messageId?.id}&teamName=${body.userChannelTeamName}&channelName=${channelName}&createdTime=${messageId?.id}`;

        context.activity.id = activityId;
        context.activity.conversation = conversation;
`

Second, we are trying to determine what kind of bot interaction is occurring based on where a bot is being mentioned:

`
        // bot is either being mentioned in a sales channel or a management channel
        const teamChannels = await TeamsInfo.getTeamChannels(context, context.activity.channelData.teamsTeamId);
        const channelArr = teamChannels.filter(channel => channel.id === context.activity.channelData.teamsChannelId);

        if (channelArr[0].name?.toLowerCase().includes("assignments") || channelArr[0].name?.toLowerCase().includes(" approvals")) {
            return "managementChannelMention"
        } else {
            return "salesChannelMention"
        }

`

As mentioned above, this error just began occurring yesterday afternoon. The code above was working before.

**Comment by jasoncheung-evbg** [comment]
Hello, we're experiencing the same issue, and our customers are being blocked from carrying out their tasks. Is it possible to expedite the investigation/resolution on the Microsoft side? Please and thank you!

**Comment by ChetanSharma-msft** [comment]
Hello Everyone, 
Sorry for delay in response.
We will look into it and let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@carolinedpena - We apologize for the delay. We have tested this on our side, and everything appears to be functioning correctly. Could you please confirm if you are still experiencing the issue?
