### ISSUE TITLE
Yeoman-Generator for Teams seems no longer actively maintained

### ISSUE THREAD

**Issue by onmomo** [MicrosoftDocs/msteams-docs#11017]
### Type of issue

Other (describe below)

### Feedback

I'm referring to [Yeoman-Generator for Teams](https://github.com/pnp/generator-teams) in the https://learn.microsoft.com/de-de/microsoftteams/platform/concepts/build-and-test/tool-sdk-overview#tools section. It seems like this project is no longer under active development. Are there plans by Microsoft to support that project or should it be removed from the docs?
Thank you Christian

### Page URL

https://learn.microsoft.com/de-de/microsoftteams/platform/concepts/build-and-test/tool-sdk-overview

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/tool-sdk-overview.md

### Author

@v-sdhakshina

### Document Id

e459f78b-748a-f230-1f52-6bd067770dcd

**Comment by Prasad-MSFT** [comment]
Hi @onmomo - Could you please let us know if you are having any trouble or getting any error while using Yeoman-Generator for Teams ?

**Comment by onmomo** [comment]
@Prasad-MSFT Hi, yes sure. So, the main issue is that the project seems no longer maintained. Therefore, my [pull request](* https://github.com/pnp/generator-teams/pull/384) that would enable support for manifest schema version 1.16 and 1.17 is not processed. Workaround this by disabling the schema validation with `--no-schema-validation
` will throw an exception in zipTask.

```
'zipTask' errored after 3 ms
[15:37:23] TypeError: Cannot read properties of undefined (reading 'outline')
    at getPackageFiles (/Users/christianmoser/workspace/integration-msteams-qa-tab/node_modules/yoteams-build-core/dist/manifest.js:178:24)
    at /Users/christianmoser/workspace/integration-msteams-qa-tab/node_modules/yoteams-build-core/dist/manifest.js:216:29
    at DestroyableTransform._transform (/Users/christianmoser/workspace/integration-msteams-qa-tab/node_modules/gulp-flatmap/index.js:51:24)
    at Transform._read (/Users/christianmoser/workspace/integration-msteams-qa-tab/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Users/christianmoser/workspace/integration-msteams-qa-tab/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/christianmoser/workspace/integration-msteams-qa-tab/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/christianmoser/workspace/integration-msteams-qa-tab/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/Users/christianmoser/workspace/integration-msteams-qa-tab/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at StreamFilter.ondata (/Users/christianmoser/workspace/integration-msteams-qa-tab/node_modules/streamfilter/node_modules/readable-stream/lib/_stream_readable.js:629:20)
    at StreamFilter.emit (node:events:513:28)

```

Therefore, we are currently looking into alternatives to this project, which is actually pity since it works quite well otherwise. If MSFT has resources to cover this project it would be great otherwise it should be removed from the docs.

**Comment by Prasad-MSFT** [comment]
Hi @pierceboggan - Could you please help here?

**Comment by ChetanSharma-msft** [comment]
Hello @onmomo - Apologies for the delay in response.

We understand that there have been no updates to the repository for some time, and we appreciate your feedback. We've informed the engineering team, and once we receive their input, we will update the documentation accordingly.

In the meantime, if you're blocked, you can explore and use the Teams Toolkit for creating applications: https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-fundamentals

Thank you for your understanding and patience.

**Comment by therealjohn** [comment]
It can be removed. The team sunset the yeoman generator. We recommend using Teams Toolkit.
