### ISSUE TITLE
Internal Server Error in Teams App Service after creating new Client Secret

### ISSUE THREAD

**Issue by roshankumar-UP** [MicrosoftDocs/msteams-docs#11589]
### Steps to reproduce

We use Teams Toolkit for VSCode for developing/provision/deployment of our Teams Bot App. 

The client secret under the Teams App Registration expired recently. We created a new client secret under the App Registration; However, an internal server error still happens in the App Service, and the Teams App (Bot App) is not working.

We've also tried the following:
1. Updated the client secret (`SECRET_BOT_PASSWORD` under `.env.production.user`) and publishing new version of the app, but that did not work.
2. Added new OAuth Connection under Bot Services > [Teams Bot App Name] > Configuration blade (Azure Active Directory as Service Provider). This did not work either.

### Expected behavior

The bot should work as expected - responding back to messages with text or adaptive cards, just like before the client secret expired.

### Actual behavior

After creating new client secret and publishing a new version of the teams app with the latest client secret, the app service still runs into internal server error whenever sending a message from the teams app, thus resulting in no response from the bot.

### Error details

```
ServerError: invalid_client:

7000215 - [2024-09-16 08:49:39Z]: AADSTS
7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '97xxxxb0'.

Trace ID: 40xxxx00
Correlation ID: 12xxxx9a

Timestamp: 2024-09-16 08:49:39Z
- Correlation ID: 12xxxx9a
- Trace ID: 40xxxx00

  at ServerError.AuthError [as constructor] (C:\home\site\wwwroot\node_modules\@azure\msal-node\node_modules\@azure\msal-common\dist\index.cjs.js:499:24)
  at new ServerError (C:\home\site\wwwroot\node_modules\@azure\msal-node\node_modules\@azure\msal-common\dist\index.cjs.js:3407:28)
  at ResponseHandler.validateTokenResponse (C:\home\site\wwwroot\node_modules\@azure\msal-node\node_modules\@azure\msal-common\dist\index.cjs.js:5442:19)
  at ClientCredentialClient.<anonymous> (C:\home\site\wwwroot\node_modules\@azure\msal-node\node_modules\@azure\msal-common\dist\index.cjs.js:6803:41)
  at step (C:\home\site\wwwroot\node_modules\@azure\msal-node\node_modules\@azure\msal-common\dist\index.cjs.js:79:23)
  at Object.next (C:\home\site\wwwroot\node_modules\@azure\msal-node\node_modules\@azure\msal-common\dist\index.cjs.js:60:53)
  at fulfilled (C:\home\site\wwwroot\node_modules\@azure\msal-node\node_modules\@azure\msal-common\dist\index.cjs.js:50:58)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
{errorCode: 'invalid_client',errorMessage: "7000215 - [2024-09-16 08:49:39Z]: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '97xxxxb0'. Trace ID: 40xxxx00 Correlation ID: 12xxxx9a Timestamp: 2024-09-16 08:49:39Z - Correlation ID: 12xxxx9a - Trace ID: 40xxxx00",subError: ''}
```

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by ChetanSharma-msft** [comment]
Hello @roshankumar-UP - Looks like you are passing Secret ID but not the value.
![image](https://github.com/user-attachments/assets/1a3754a1-355b-4c67-a172-c5b934549565)

Please check your configuration and update it once.

Please let us know if you still facing this issue.

**Comment by roshankumar-UP** [comment]
Hello @ChetanSharma-msft,

We used the secret value. After the old one expired, we created a new client secret. We then copied the secret value since it's only visible for once after creation, and used it for `SECRET_BOT_PASSWORD` value in `.env.production.user` file in our teams app repository. Even then, it gave the same error.

For now, we provisioned new resources and changed the `BOT_ID`, `BOT_DOMAIN` and `BOT_AZURE_APP_SERVICE_RESOURCE_ID`, while keeping the old `TEAMS_APP_ID` and `TEAMS_APP_PUBLISHED_APP_ID` so that we can use the existing published app with the new provisioned resources.

But because of this, the teams app has been down for four working days and we're still waiting on validation; and if I am correct, this approach also means user's chat history will be lost, and we'll eventually run into this issue once the client secret expires again.

Can you let us know if this is an issue on MSFT Teams end, and if/when it will be resolved? or did our approach of changing the client secret had issues?

**Comment by ChetanSharma-msft** [comment]
Hello @roshankumar-UP - As discussed over call, this issue is fixed after updating bot secret in App service configuration.
Please let us know if you need further assistance.

Please share your valuable feedback [here](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u).

**Comment by roshankumar-UP** [comment]
Hello @ChetanSharma-msft - very thankful to you for spending your time debugging this issue to the end, and providing an answer as to how to tackle this if it happens again. For anyone searching for this issue, the solution was to go to App Service >  [App Service Name] > Environment Variables > update the `BOT_PASSWORD` with the new client secret.

One recommendation that I can provide, is that although the issue in itself is a single environment variable change, we failed to identify it on our own because we failed to find correlation between the Client Secret used by the Scaffolded Teams app, and the Bot Password of the App Service involved...

Maybe this was pointed out in documentation and we missed it; but it also means someone else will miss it in the future as well. We hope the documentation for scaffolded teams bot app, and teams apps in general, gets improvements and include highlighted points for issues like this, which have a potential to cause production apps to go down.
