### ISSUE TITLE
[Parse] Unknown element type "CodeBlock". Fallback will be used if present.

### ISSUE THREAD

**Issue by ryeleo** [MicrosoftDocs/msteams-docs#11901]
### Type of issue

Code doesn't work

### Feedback

I'm testing "CodeBlock" in my adaptive card, but it is failing to render with the following exception:

```
Microsoft.Azure.ProcessSimple.Data.Entities.Exceptions.ProcessSimpleDataException: The specified Teams flowbot adaptive card request is missing or invalid. The tracking Id is '{0}'. ---> System.InvalidCastException: Unable to cast object of type 'AdaptiveCards.AdaptiveUnknownAction' to type 'AdaptiveCards.AdaptiveElement'.
   at AdaptiveCards.IgnoreEmptyItemsConverter`1.<>c.<ReadJson>b__1_3(Object value)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at AdaptiveCards.AdaptiveTypedElementConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at AdaptiveCards.AdaptiveCardConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AdaptiveCards.AdaptiveCard.FromJson(String json)
   at Microsoft.Azure.ProcessSimple.Data.Components.AdaptiveCards.AdaptiveCardBuilder.DeserializeAdaptiveCard(String serializedAdaptiveCard, RequestIdentity requestor, CultureInfo cultureInfo, BotAdaptiveCardAtMentions atMentions) in C:\__w\1\s\src\processsimple\Roles\ProcessSimple.Data\Components\AdaptiveCards\AdaptiveCardBuilder.cs:line 750
   --- End of inner exception stack trace ---
   at Microsoft.Azure.ProcessSimple.Data.Components.AdaptiveCards.AdaptiveCardBuilder.DeserializeAdaptiveCard(String serializedAdaptiveCard, RequestIdentity requestor, CultureInfo cultureInfo, BotAdaptiveCardAtMentions atMentions) in C:\__w\1\s\src\processsimple\Roles\ProcessSimple.Data\Components\AdaptiveCards\AdaptiveCardBuilder.cs:line 754
   at Microsoft.Azure.ProcessSimple.Web.Common.Validation.BotAdaptiveCard(String card, RequestIdentity senderRequestIdentity) in C:\__w\1\s\src\processsimple\Roles\ProcessSimple.Data\Common\Validation\BotValidation.cs:line 943
```

When I try to paste the example CodeBlock from this document into [MSFT Adaptive Card Designer (v1.5)](https://adaptivecards.io/designer/), I get the following error:

```
[Parse] Unknown element type "CodeBlock". Fallback will be used if present.
```

![Screenshot of "Unknown element type "CodeBlock"" error in MSFT Adaptive Card Designer (v1.5)](https://github.com/user-attachments/assets/0ab73caf-87ed-473d-a9fd-daa53d8d0d55)

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cdesktop1%2Cdesktop2%2Cconnector-html

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/cards-format.md

### Author

@surbhigupta

### Document Id

e5f5f69e-66e9-d1b2-e19a-485d0ffcd6fa

**Comment by Meghana-MSFT** [comment]
@ryeleo - We sent the above-mentioned card through bot and it is rendering fine in Teams Desktop. Could you please let us know how you are sending the card and testing this.

![image](https://github.com/user-attachments/assets/8e9ba4c4-67e4-4a7d-a632-fd0d5cab0c10)
