### ISSUE TITLE
Error when trying to create the app service

### ISSUE THREAD

**Issue by Navyjetfixer** [MicrosoftDocs/msteams-docs#286]
I am logged into my Azure account. When attempting to create the app service received the following error:

System.Net.Http.HttpRequestException: {"error":{"code":"AuthorizationFailed","message":"The client 'giguim@microsoft.com' with object id 'e49920c6-73a5-4c60-bd40-79ef138cf5bd' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/write' over scope '/subscriptions/5daaa09b-c21c-46f3-ad4a-a2077e71e2d3/resourcegroups/myResourceGroup'."}}
   at Microsoft.VisualStudio.Web.WindowsAzure.Provisioning.ResourceProvisioningControlModel.&lt;ThrowOnUnexpectedStatusCode&gt;d__174.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Client.ARMCaller.HttpResponseExtensions.&lt;DeserializeEntityJsonAsync&gt;d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Client.ARMCaller.ARMRootExtensions.&lt;DeserializeEntityAsync&gt;d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Client.ARMCaller.EntityExtensions.&lt;PutAsync&gt;d__25`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Web.WindowsAzure.Provisioning.ResourceProvisioningControlModel.&lt;DeferredDeploymentRunner&gt;d__176.MoveNext()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d2cee61-876f-cb0f-61bd-349356e79491
* Version Independent ID: d2fd1aff-2d1d-6c5d-e75f-64d81085a1e0
* Content: [Host your Teams app in Azure - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-in-azure)
* Content Source: [msteams-platform/get-started/get-started-dotnet-in-azure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-dotnet-in-azure.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
How does this relate to MIcrosoft Teams?

**Comment by Navyjetfixer** [comment]
I was following the hello world tutorial for creating an app in Teams. I reached this point and had this error and could not proceed. I do not know if this error was due to the example files I am using, the instructions I am following or something with my Azure account. I could not find much on this error on the internet.

**Comment by billbliss** [comment]
I just tried it and it worked fine - this is a problem with the Azure account you are logged in with. It doesn't have permissions to do something on whatever it picked by default to do it on.

Do you have more than one Azure account? Or maybe it's brand new? [This query](https://www.bing.com/search?FORM=U147DF&PC=U147&q=azure+The+client+with+object+id+does+not+have+authorization+to+perform+action+subscriptions%2Fresourcegroups%2Fwrite+over+scope+%2Fsubscriptions%2F) surfaced a lot of good results.

**Comment by Navyjetfixer** [comment]
Yes, this does work locally and with ngrok. This account is not new, and I have run some IOT projects on Azure with this account. So now I need to figure out why I am being blocked in Azure. Thank you for your help.

**Comment by billbliss** [comment]
There's something about how the defaults are set that's messing up - I don't know how to reverse engineer the resource group or subscription IDs unfortunately. If you find anything please let us know - you may not be the first to run into this.

**Comment by Navyjetfixer** [comment]
In the Create App Service screen under Subscription, I was picking the wrong one. It was showing me several that I do not even have access too. Once I picked the correct one it worked fine.
