### ISSUE TITLE
Unhandled promise rejections and deprecation warnings

### ISSUE THREAD

**Issue by echo083** [MicrosoftDocs/msteams-docs#4100]
Hello,

When I launch teams from the command line, I get the warnings and errors below.
I didn't notice any bugs related to these errors and warnings but I wanted to report it for information and eventual fix.

Thanks

(node:8100) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at C:\Users\admziu\AppData\Local\Microsoft\Teams\current\resources\app.asar\node_modules\ipc-monitor\renderer\dom-observables.js:31:5
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\admziu\AppData\Local\Microsoft\Teams\current\resources\app.asar\node_modules\ipc-monitor\renderer\dom-observables.js:30:30)
    at Module._compile (C:\Users\admziu\AppData\Local\Microsoft\Teams\current\resources\app.asar\external\v8-compile-cache\v8-compile-cache.js:192:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (C:\Users\admziu\AppData\Local\Microsoft\Teams\current\resources\app.asar\external\v8-compile-cache\v8-compile-cache.js:173:28)
(node:8100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(electron) 'systemPreferences.isInvertedColorScheme()' is deprecated and will be removed. Please use 'nativeTheme.shouldUseInvertedColorScheme' instead.
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:8100) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:8100) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 appInitialized listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:8100) UnhandledPromiseRejectionWarning: undefined
(node:8100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8100) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ecsSettingsUpdated listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:8100) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'logInfoToFile' of undefined
    at EventEmitter.showPreviewInToastsEnabledRequestHandler (C:\Users\admziu\AppData\Local\Microsoft\Teams\current\resources\app.asar\lib\notifications\NotificationEventManager.js:133:29)
    at EventEmitter.emit (events.js:215:7)
    at EventingService.emit (C:\Users\admziu\AppData\Local\Microsoft\Teams\current\resources\app.asar\lib\eventingService.js:14:28)
    at SettingsService.compareSettingsData (C:\Users\admziu\AppData\Local\Microsoft\Teams\current\resources\app.asar\lib\settingsService.js:635:43)
    at SettingsService.processSettingsData (C:\Users\admziu\AppData\Local\Microsoft\Teams\current\resources\app.asar\lib\settingsService.js:488:18)
    at SettingsService.<anonymous> (C:\Users\admziu\AppData\Local\Microsoft\Teams\current\resources\app.asar\lib\settingsService.js:430:18)
    at Generator.next (<anonymous>)
    at C:\Users\admziu\AppData\Local\Microsoft\Teams\current\resources\app.asar\lib\settingsService.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\admziu\AppData\Local\Microsoft\Teams\current\resources\app.asar\lib\settingsService.js:4:12)
(node:8100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

**Comment by Prithvi-MSFT** [comment]
Hi @echo083 ,
Can you share steps to repro this issue like which command you are executing on cmd ? Also can you share document details you are referring to ?

**Comment by echo083** [comment]
Hello,

Please see my screenshots with the details of the cmd, teams version and system information :
![cmd](https://user-images.githubusercontent.com/10560975/132201902-0f79736a-b23d-42e0-9d2c-0b0125dd7609.png)
![version](https://user-images.githubusercontent.com/10560975/132201926-74ff5b92-f315-420e-a3d4-9cdd6b96368f.png)
![system_information](https://user-images.githubusercontent.com/10560975/132201934-3de01045-0202-49f1-ba54-ad3ea20da12d.png)

Let me know if you require additional information.
As I don't see the source code of the files reported in the errors and warnings it's not sure that a fix is required so I would let you the appreciation of any fix requirement and would understand if my ticket is closed without any action. :)

Thanks

**Comment by Prithvi-MSFT** [comment]
Hi @echo083 ,
We are not able to repro this issue. We tried this in windows 10 with teams version 1.4 and it is working for us. Can you try the same on upgraded version ?

Also we are mostly responsible Microsoft Teams App development queries and this does not seem to be related to it.

Thanks for understanding

**Comment by echo083** [comment]
Hello,

When I launch teams from the command line on my barebone windows 10 computer I don't have any error or warning.
My assumption is that these errors are related to my vmware virtual environment which you certainly don't officially support.

_Also we are mostly responsible Microsoft Teams App development queries and this does not seem to be related to it._
Sorry I thought it was the appropriate place to submit my bug report.
So should I close my ticket? I'd remain available anytime to test any new release or fix if interested.

Thanks

**Comment by Prithvi-MSFT** [comment]
Hi echo083,'
You can close this issue since its working on windows 10. You can reopen it if it fails further for windows 10.

Thanks
