### ISSUE TITLE
Operation returned an invalid StatusCode "Bad Gateway"

### ISSUE THREAD

**Issue by KKMicrosoft** [MicrosoftDocs/msteams-docs#4799]
Hello,

We are intermittently seeing an issue being thrown from Botframework

Microsoft.Bot.Connector.ErrorResponseException: Operation returned an invalid status code 'BadGateway'
   at Microsoft.Bot.Connector.Conversations.<GetConversationMembersWithHttpMessagesAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.ConversationsExtensions.<GetConversationMembersAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

The issue seems to be somewhat related to this issue from before -> [Link](https://github.com/MicrosoftDocs/msteams-docs/issues/3561)

**Comment by sayali-MSFT** [comment]
@KKMicrosoft - We are looking into this I will get back to you soon.

**Comment by v-chetsh** [comment]
@KKMicrosoft - Could you please check on below documentation:
Throttling limits for sending messages from Bot is documented here in [Optimize your bot with rate limiting in Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit#per-bot-per-thread-limit).

**Comment by sayali-MSFT** [comment]
@KKMicrosoft - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by sayali-MSFT** [comment]
@KKMicrosoft - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?
