### ISSUE TITLE
Can't post a card attachment with startReplyChain

### ISSUE THREAD

**Issue by danchoi** [MicrosoftDocs/msteams-docs#576]
Please let me know if this is the wrong place to post this question. 

I can successfully post a "proactive" message to a channel with the NodeJS library, but as soon as I try to add a card as an attachment to the message doesn't post at all. 

```
const card = new teams.O365ConnectorCard()
      .title("test connector card")
      .text("some text")

const message = new teams.TeamsMessage()
    .text(`testing posted message ${new Date()} from builder`)
    .addAttachment(card.toAttachment()) // If I don't do this, it works

connector.startReplyChain(serviceUrl, channelId, message, (err, address) => {
  console.log("received err", err)
  console.log("received address", address)
})
```
The error I get is

```
received err Error: Failed to start reply chain: no conversation ID and activity ID returned.
    at innerCallback (/home/choi/m/msteams/hello-world/node_modules/botbuilder-teams/lib/TeamsChatConnector.js:180:37)
    at /home/choi/m/msteams/hello-world/node_modules/botbuilder-teams/lib/RemoteQuery/teams.js:461:20
    at retryCallback (/home/choi/m/msteams/hello-world/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:85:9)
    at retryCallback (/home/choi/m/msteams/hello-world/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:135:9)
    at handleRedirect (/home/choi/m/msteams/hello-world/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
    at Request._callback (/home/choi/m/msteams/hello-world/node_modules/ms-rest/lib/requestPipeline.js:126:16)
    at Request.self.callback (/home/choi/m/msteams/hello-world/node_modules/ms-rest/node_modules/request/request.js:187:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/choi/m/msteams/hello-world/node_modules/ms-rest/node_modules/request/request.js:1044:10)
received address null
```

**Comment by Wajeed-msft** [comment]
@daauro - Could you please try this code? I have removed message text.

```
        const card = new teams.O365ConnectorCard()
            .title("test connector card")
            .text("some text")
            .summary('test connector card');

        var message = new teams.TeamsMessage(session)
        .attachments([card.toAttachment()]);
        connector.startReplyChain(session.message.address.serviceUrl, channelId, message, function (err, address) {
            if (err) {
                console.log(err);
                session.endDialog('There is some error');
            }
            else {
                var msg = new teams.TeamsMessage(session)
                .text('Reply to main conversation')
                .address(address);
                session.send(msg);
                session.endDialog();
            }
            });
```

**Comment by danchoi** [comment]
@Wajeed-msft thank you. Yes, it works when you remove the text from the `TeamsMessage()`
