### ISSUE TITLE
MsTeams chatbot sometimes fails to retrieve a username

### ISSUE THREAD

**Issue by PauwelsYoran** [MicrosoftDocs/msteams-docs#629]
I have Microsoft chatbot right now who needs to get the username.  When I use: `string vStrName = turnContext.Activity.From.Name;` it works for some people but for some it just returns an empty string. Any ideas what de problem might be and how to solve it.

The chatbot is deployed as a bot in the teams tennant store.

**Comment by Wajeed-msft** [comment]
Could you please check if [team roaster](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-context#fetching-the-team-roster) gives proper names for those users?

**Comment by PauwelsYoran** [comment]
When i try to fetch themthe chatbot crashes immediately and i get follwing error. If comment the code the chatbot works

Sorry, it looks like something went wrong.System.TypeLoadException: Could not load type ‘Microsoft.Bot.Connector.ChannelAccount’ from assembly ‘Microsoft.Bot.Connector, Version=4.4.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35’.
at Microsoft.BotBuilderSamples.ChatBot.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityInternalAsync(ITurnContext turnContext, BotCallbackHandler callback, Int32 nextMiddlewareIndex, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\MiddlewareSet.cs:line 73
at Microsoft.Bot.Builder.MiddlewareSet.<>c__DisplayClass4_0.<ReceiveActivityInternalAsync>b__0(CancellationToken ct) in d:\a\1\s\libraries\Microsoft.Bot.Builder\MiddlewareSet.cs:line 82
at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.<OnTurnAsync>d__0.MoveNext() in d:\a\1\s\libraries\Microsoft.Bot.Builder\BotFrameworkAdapter.cs:line 964
— End of stack trace from previous location where exception was thrown —
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.MiddlewareSet.<ReceiveActivityWithStatusAsync>d__3.MoveNext() in d:\a\1\s\libraries\Microsoft.Bot.Builder\MiddlewareSet.cs:line 55
— End of stack trace from previous location where exception was thrown —
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.BotAdapter.<RunPipelineAsync>d__13.MoveNext() in d:\a\1\s\libraries\Microsoft.Bot.Builder\BotAdapter.cs:line 167

Sorry, it looks like something went wrong.System.TypeLoadException: Could not load type ‘Microsoft.Bot.Connector.ChannelAccount’ from assembly ‘Microsoft.Bot.Connector, Version=4.4.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35’.
at Microsoft.BotBuilderSamples.ChatBot.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityInternalAsync(ITurnContext turnContext, BotCallbackHandler callback, Int32 nextMiddlewareIndex, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\MiddlewareSet.cs:line 73
at Microsoft.Bot.Builder.MiddlewareSet.<>c__DisplayClass4_0.<ReceiveActivityInternalAsync>b__0(CancellationToken ct) in d:\a\1\s\libraries\Microsoft.Bot.Builder\MiddlewareSet.cs:line 82
at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.<OnTurnAsync>d__0.MoveNext() in d:\a\1\s\libraries\Microsoft.Bot.Builder\BotFrameworkAdapter.cs:line 964
— End of stack trace from previous location where exception was thrown —
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.MiddlewareSet.<ReceiveActivityWithStatusAsync>d__3.MoveNext() in d:\a\1\s\libraries\Microsoft.Bot.Builder\MiddlewareSet.cs:line 55
— End of stack trace from previous location where exception was thrown —
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.BotAdapter.<RunPipelineAsync>d__13.MoveNext() in d:\a\1\s\libraries\Microsoft.Bot.Builder\BotAdapter.cs:line 167

I used following code to fetch them:
``
var connector = new ConnectorClient(new Uri(turnContext.Activity.ServiceUrl));
                    var members = await connector.Conversations.GetTeamsConversationMembersAsync(turnContext.Activity.Conversation.Id);

                    string tmpStr = "";

                    foreach (TeamsChannelAccount account in members)
                    {
                        tmpStr = tmpStr + " " + account.GivenName + " " + account.Surname;
                    }

                    await LogDataAsync("namelog", tmpStr, turnContext, "0");

                    if (members.Length > 1)
                    {
                        await LogDataAsync("namelog", "Name of user by using members: " + vStrName, turnContext, "0");
                        this.username = members[1].GivenName + members[1].Surname;
                    }
``

**Comment by PauwelsYoran** [comment]
I was able to check the team roster using postman, and there the usernames were correct

**Comment by PauwelsYoran** [comment]
Is it possible that is has something to do with the first time a user uses the bot apllication? Most of the times this occures after the chatbot is installed and used for the first time.

**Comment by PauwelsYoran** [comment]
i found that when the chatbot is used for the first time, after installation as bot app, it gets an empty strin for the username. When i forced it to retrieve the name for a second time the problem was solved.
