### ISSUE TITLE
"gulp" command not working to generate the zip file

### ISSUE THREAD

**Issue by peterremote1980** [MicrosoftDocs/msteams-docs#661]
/Users/peter/Desktop/msteams-samples-hello-world-nodejs&gt;gulp
/Users/peter/Desktop/msteams-samples-hello-world-nodejs/gulpfile.js:18
gulp.task('default', gulp.series('clean', 'generate-manifest'), function(done) {
                          ^

TypeError: gulp.series is not a function
    at Object.&lt;anonymous&gt; (/Users/peter/Desktop/msteams-samples-hello-world-nodejs/gulpfile.js:18:27)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at execute (/usr/local/lib/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:28:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/node_modules/gulp-cli/index.js:201:24)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33cdb816-f2b6-31a4-0e4c-d730435d0a6b
* Version Independent ID: c111eaef-ac66-e245-b2bc-623c1801a7db
* Content: [Get started with App Studio and Node.js - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-app-studio?view=msteams-client-js-latest#feedback)
* Content Source: [msteams-platform/get-started/get-started-nodejs-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-nodejs-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Please make sure you are using version 4.0.0 of Gulp or later.

**Comment by butchmarshall** [comment]
the devDependency in the package.json is still specifying gulp ^3.9.1

**Comment by roalexan** [comment]
Don't know if this is related, but I hit a gulp error. This is what worked for me:

				ERROR:
					[11:35:33] Using gulpfile C:\microsoft\repos\msteams-samples-hello-world-nodejs\gulpfile.js
					C:\Users\roalexan\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129
						gulpInst.start.apply(gulpInst, toRun);
									   ^

					TypeError: Cannot read property 'apply' of undefined
						at C:\Users\roalexan\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
						at process._tickCallback (internal/process/next_tick.js:61:11)
						at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
						at startup (internal/bootstrap/node.js:283:19)
						at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
				FIX:
					needed to do: npm install --global gulp-cli (see: https://www.liquidlight.co.uk/blog/how-do-i-update-to-gulp-4/)
