### ISSUE TITLE
How to update an adaptive card which is already sent in channel from BOT?

### ISSUE THREAD

**Issue by XimenaWang** [MicrosoftDocs/msteams-docs#703]
Hi team,
My Bot sent the adaptive card with button in channel , after I clicking on button. my Bot API will receive the Activity model(contains ConversationId and ActivityId). I can update the adaptive card by these two parameters using UpdateActivityAsync.   
my API snippet:
![image](https://user-images.githubusercontent.com/30890958/58853893-906bcb80-8650-11e9-917f-ebf2889c05d1.png)

but I got the **exception** as below, I am not sure what I am missing, could you please take one look, thanks in advance!

Microsoft.Rest.HttpOperationException: Unknown
   at Microsoft.Bot.Connector.ErrorHandling.<HandleErrorAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.ConversationsExtensions.<UpdateActivityAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TeamsToDoAppConnector.Controllers.MessagesController.<Post>d__0.MoveNext() in E:\p_CTM\BingLSE\private\lseprod\TeamsConnectorAndBot\TeamsToDoAppConnector\Controllers\MessagesController.cs:line 64

**Comment by XimenaWang** [comment]
I update the adaptive card successfully! this function needs parameters is **Recipient Id** instead of **Activity Id**
![image](https://user-images.githubusercontent.com/30890958/58945321-7f968500-8738-11e9-81d3-9f0a546a1664.png)
