### ISSUE TITLE
Impossible to update activity for Messaging Extension card

### ISSUE THREAD

**Issue by Leks12lk** [MicrosoftDocs/msteams-docs#944]
Hi,
I have ME adaptive card. Some elements of that card contain SelectAction property. By clicking to that SelectAction the some logic is done in code and as a result there should be updated activity (activity in this case means the card that was sent to chat from ME). When attempt to update that card I got the exception with message **"Operation returned an invalid status code 'BadRequest'"**. The stack trace is the next 
```
at Microsoft.Bot.Connector.Conversations.UpdateActivityWithHttpMessagesAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

To update activity I use the next code. All necessary properties such as Conversation.Id, ReplyToId of activity object exist.

```
public async Task MyMethod(ITurnContext turnContext, string someString)
{
        var attachment = await BuildAttachment(turnContext, someString);

        if (attachment != null)
        {               
            var activity = turnContext.Activity;
               
            var message = activity.CreateReply();
            message.Attachments.Add(attachment);

            await turnContext.TurnState.Get<IConnectorClient>().Conversations.UpdateActivityWithHttpMessagesAsync(
                activity.Conversation.Id,
                activity.ReplyToId,
                message);
        }
 }
```

Please note this code works fine for card that was sent by bot (not from ME).

Is it possible to update the card sent from ME?

**Comment by Gousia-MSFT** [comment]
@Leks12lk It is not possible to update the card sent from ME because a Message Extension card is sent by a user and bot cannot update the card which is sent by a user.
